-d /Users/bryce/Documents/GitHub/Gowin-LCD-Drive-Demo/impl/gwsynthesis/Gowin-LCD-Drive-Demo.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /Users/bryce/Documents/GitHub/Gowin-LCD-Drive-Demo/src/top.cst
-cfg /Users/bryce/Documents/GitHub/Gowin-LCD-Drive-Demo/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
